portfolio/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name='home'),
    path('Projects/', views.projects, name='projects'),
    path('Projects/<str:project_id>', views.view_project, name='view_project'),
    path('Achievements/', views.achievements, name='achievements'),
    path('Resume/', views.resume, name='resume'),
    # Delete this later
    path('bs/', views.bs, name='bs')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

portfolio/main/models.py
from django.db import models

class aboutMe(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    media_url = models.URLField(blank=True, null=True)
    button_url = models.URLField(blank=True, null=True)
    button_text = models.CharField(max_length=255, blank=True, null=True)
    is_video = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class aboutMeExperiences(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=512)
    image = models.ImageField(upload_to='static/media', blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_image(self):
        if self.image:
            return self.image.url
        return self.image_url

class MoreExperience(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    media_url = models.URLField(blank=True, null=True)
    button_url = models.URLField(blank=True, null=True)
    button_text = models.CharField(max_length=255, blank=True, null=True)
    is_video = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image_url = models.URLField(blank=True, null=True)
    github_link = models.URLField()
    tags = models.CharField(max_length=200, blank=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CertificationCategory(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Certification Categories"

    def __str__(self):
        return self.name


class Certification(models.Model):
    category = models.ForeignKey(CertificationCategory, on_delete=models.CASCADE, related_name="certifications")
    image = models.ImageField(upload_to="static/media", blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.category.name}"

    def get_image(self):
        if self.image:
            return self.image.url
        return self.image_url

portfolio/main/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from django.http import HttpResponse

# Create your views here.
def home(request):
	about_me = aboutMe.objects.all()
	experiences = aboutMeExperiences.objects.all()
	more_experiences = MoreExperience.objects.all()
	huawei_category = CertificationCategory.objects.filter(name__iexact="Huawei").first()
	return render(request, "main/home.html",{
		"about_me":about_me,
		'experiences': experiences,
		"more_experiences": more_experiences,
		"huawei_category": huawei_category
	})

def projects(request):
	all_projects = Project.objects.all().order_by('-last_updated')
	context = {
        'projects': all_projects
    }
	return render(request, "main/projects.html", context)

def view_project(request, project_id):
	project = Project.objects.get(id=project_id)
	repo_name = str(project.github_link).split('/')[4].split('.')[0]
	return render(request, "main/view_project.html", {
		"project":project,
		"repo_name":repo_name,
		})

def achievements(request):
	categories = CertificationCategory.objects.prefetch_related("certifications").all()
	context = {"categories":categories}
	return render(request, "main/achievements.html", context)

def resume(request):
	context = {}
	return render(request, "main/resume.html", context)

# Delete this later
def bs(request):
	return JsonResponse({'bs': "gs' bs 'k' bs '_' bs 't8PwbwlR' bs '870lI5L2Gjc7WGdy' bs 'b3FYi3ijadcC' bs 'hlLcJeZX3eZZblRo"})

portfolio/main/templates/main/achievements.html
{% extends 'main/layout.html' %}
{% load static %}
{% block header %}
    <title>Achievements</title>
{% endblock %}
{% block content %}
    <canvas id="bgCanvas"></canvas>
    <div class="video-container">
        <video autoplay muted loop playsinline class="video-bg-2">
            <source src="https://i.imgur.com/VRckACz.mp4" type="video/mp4">
        </video>
        <div class="overlay"></div>
        <div class="content text-center p-md-0 p-2 hidden">
            <h1 class="font-1 text-danger">Milestones & Achievements</h1>
            <p class="font-2 text-white lead">A glimpse into the milestones I’ve been fortunate to achieve along my journey.</p>
        </div>
    </div>

    <!-- Fullscreen Overlay -->
    <div class="overlay-fullscreen" id="overlay" onclick="closeFullscreen()">
        <img id="fullscreen-img" src="">
    </div>

    <!-- Dynamic Categories -->
    {% for category in categories %}
    <div class="container mt-5">
        <h1 class="font-1 py-3 px-1 hidden slide-right">
            {% if "Huawei" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% elif "IBM" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% elif "Volunteer" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% elif "FreeCodeCamp" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% elif "Artificial Intelligence Club" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% elif "DeepLearning.AI" in category.name %}<span class="text-danger">{{ category.name }}</span>
            {% else %}{{ category.name }}
            {% endif %} Certifications
        </h1>
        <section class="row d-flex justify-content-center align-items-center">
            {% for cert in category.certifications.all %}
            <div class="col-md-4 col-6 p-3 hidden slide-right" style="max-height: 80vh;">
                <img src="{{ cert.get_image }}" alt="Certification"
                     class="shadow achievement-img"
                     onclick="toggleFullscreen(this)"
                     style="max-width: 100%; max-height: 100%; object-fit: contain;">
            </div>
            {% endfor %}
        </section>
    </div>
    {% endfor %}

    <div class="mb-5"></div>

{% endblock %}

portfolio/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block header %}{% endblock %}
        <link rel="stylesheet" href="{% static 'main/style.css' %}">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Italiana&family=Prata&family=STIX+Two+Text:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
        <!-- Animate.style -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand font-2" href="{% url 'main:home' %}">Abdulla Shahzan</a>
                <button class="btn btn-outline-none text-light fs-2 d-block d-md-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto font-2">
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'main:home' %}"><i class="bi bi-person-circle me-2"></i>Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'projects' %}active{% endif %}" href="{% url 'main:projects' %}"><i class="bi bi-code-slash me-2"></i>Work</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'achievements' %}active{% endif %}" href="{% url 'main:achievements' %}"><i class="bi bi-patch-check me-2"></i>Certifications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer class="bg-dark text-light text-center p-5">
            <div class="container">
                <p class="mb-0 font-2 lead">&copy; 2025 All rights reserved.</p>
            </div>
            <div class="container mt-3">
                <a href="https://www.linkedin.com/in/abdulla-shahzan-03b00a226?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" class="text-decoration-none text-danger"><i class="bi bi-linkedin me-2"></i><span class="font-2">Connect with me</span></a>
            </div>
        </footer>
        <script src="{% static 'main/script.js' %}"></script>
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    </body>
</html>

portfolio/main/templates/main/projects.html
<!-- main.html -->
{% extends 'main/layout.html' %}
{% load static %}
{% block header %}
    <title>My Projects</title>
{% endblock %}
{% block content %}
    <canvas id="bgCanvas"></canvas>
    <div class="video-container">
        <video autoplay muted loop playsinline class="video-bg-2">
            <source src="https://i.imgur.com/urTsTII.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div class="overlay"></div>
        <div class="content text-center animate__animated hidden">
            <h1 class="font-1 text-danger">A collection of work reflecting on my practical experience.</h1>
            <p class="font-2 text-white lead">Each project represents the small steps taken toward creating meaningful solutions.</p>
        </div>
    </div>
    <div class="container mt-5">
        <div class="masonry">
            {% for project in projects %}
                <div class="col">
                    <div class="card shadow-lg hidden slide-right">
                        <img src="{{ project.image_url }}" class="card-img-top hidden" alt="{{project.image_url}}">
                        <div class="card-body">
                            <h4 class="card-title font-2 hidden">{{ project.title }}</h4>
                            <hr>
                            <p class="card-text font-2 hidden clamp-3">{{ project.description }}</p>
                            <p class="card-text font-2 hidden"><strong>Tags:</strong> {{ project.tags }}</p>
                            <a href="{% url 'main:view_project' project.id %}" class="btn btn-dark hidden"><i class="bi bi-card-text me-2"></i><span class="font-2">Read more</span></a>
                            <a href="{{ project.github_link }}" class="btn btn-danger hidden" target="_blank" rel="noopener noreferrer">
                                <i class="bi bi-github me-2"></i><span class="font-2">View Project</span>
                            </a>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary hidden">Last updated {{ project.last_updated|date:"M d, Y" }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mb-5"></div>
{% endblock %}

portfolio/main/templates/main/resume.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Resume - Abdulla Shahzan</title>
        <link rel="stylesheet" href="{% static 'main/style.css' %}">
        <link rel="stylesheet" href="{% static 'main/resume.css' %}">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Italiana&family=Prata&family=STIX+Two+Text:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
        <!-- Animate.style -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    </head>
    <body>
        <button class="btn btn-danger shadow-lg no-print" onclick="window.print()" style="position: fixed; top: 20px; right: 20px;"><i class="bi bi-download me-2"></i><span class="font-2">Download</span></button>
        <div class="container-fluid shadow-lg">
            <div class="row mb-1">
                <div class="container-fluid bg-dark text-light px-5 pt-4 pb-1">
                    <article>
                        <h1 class="font-1 text-danger">Abdulla Shahzan</h1>
                        <h4 class="font-2" style="margin-top: -10px;">MLOps & Cloud Solutions Architect</h4>
                        <p class="font-2">+966508382675 <span class="text-danger">|</span> abdullashahzan@gmail.com <span class="text-danger">|</span> myportfolioshahzan.pythonanywhere.com</p>
                    </article>
                </div>
            </div>
            <div class="row px-3 mb-1 mt-4">
                <div class="container-fluid row">
                    <article>
                        <h4 class="fw-bold font-3 mb-3"><i class="bi bi-card-heading me-3"></i>PROFESSIONAL SUMMARY</h4>
                        <hr>
                        <p class="font-2"><strong>Saudi National Champion</strong> and <strong>Top 3 in Middle East & Central Asia</strong> in Huawei Global ICT Competition for Cloud and AI. I architect and engineer cloud-native AI solutions with the proven excellence required to compete at the highest technical levels.</p>
                    </article>
                </div>
            </div>
            <div class="row px-3 mb-2">
                <div class="container-fluid row">
                    <article class="col-md-6 mb-md-0 mb-3">
                        <h4 class="fw-bold font-3 mb-2"><i class="bi bi-book me-3"></i>EDUCATION</h4>
                        <hr>
                        <div class="row pt-2">
                            <article class="mb-1">
                                <h5 class="font-2">KAUST Academy</h5>
                                <p class="font-2" style="margin-top: -10px;">Machine Learning and Data Science</p>
                            </article>
                            <article class="mb-1">
                                <h5 class="font-2">King Khalid University</h5>
                                <p class="font-2" style="margin-top: -10px;">Bachelor of Science in Computer Engineering</p>
                                <p class="font-2" style="margin-top: -20px;">GPA: <strong>4.82</strong> / 5.0</p>
                            </article>
                            <article>
                                <h5 class="font-2">New Middle East International School</h5>
                                <p class="font-2" style="margin-top: -10px;">Primary, Secondary and Highschool</p>
                                <p class="font-2" style="margin-top: -20px;">Percentage: <strong>92.4%</strong></p>
                            </article>
                        </div>
                    </article>
                    <article class="col-md-6">
                        <h4 class="fw-bold font-3 mb-3"><i class="bi bi-award me-3"></i>CERTIFICATIONS</h4>
                        <hr>
                        <ul class="font-2" style="list-style: square;">
                            <li>Mathematics for Machine Learning and Data Science - <span class="text-danger">DeepLearning.AI</span></li>
                            <li>Applied Data Science - <span class="text-danger">IBM</span></li>
                            <li>Cloud Computing & Services - <span class="text-danger">Huawei ICT academy</span></li>
                            <li>Scientific Computing with Python - <span class="text-danger">freecodecamp</span></li>
                            <li>100 Volunteer Hours - <span class="text-danger">National Center for Non-Profit Sector</span></li>
                        </ul>
                    </article>
                </div>
            </div>
            <div class="row mb-2 px-3">
                <div class="container-fluid row">
                    <article>
                        <h4 class="fw-bold font-3 mb-3"><i class="bi bi-person-workspace me-3"></i>PROJECTS</h4>
                        <hr>
                        <ul class="font-2" style="list-style: square; margin-left: -10px;">
                            <li>Deep learning AI model for mineral processing and exploration on saline water simulation.</li>
                            <li>Deployed a scalable and resilient microservice architecture application on Huawei Cloud using kubernetes along with VPC peering, database management, disaster recovery implementation, highly reliable network service architecture such as load balancing, vpn services, SNAT/DNAT, ACL etc</li>
                            <li>Enterprise-grade ecommerce web application with django and google firebase.</li>
                        </ul>
                    </article>
                </div>
            </div>


            <div class="row mb-1 px-3">
                <div class="container-fluid row">
                    <article class="col-md-7 mb-md-0 mb-3">
                        <h4 class="fw-bold font-3 mb-3"><i class="bi bi-braces me-3"></i>TECHNICAL SKILLS</h4>
                        <hr>
                        <div class="container-fluid">
                            <div class="d-flex flex-wrap gap-2">
                                <span class="border px-2 py-1 rounded font-2">Kubernetes</span>
                                <span class="border px-2 py-1 rounded font-2">PyTorch</span>
                                <span class="border px-2 py-1 rounded font-2">Tensorflow</span>
                                <span class="border px-2 py-1 rounded font-2">Linux</span>
                                <span class="border px-2 py-1 rounded font-2">Python</span>
                                <span class="border px-2 py-1 rounded font-2">Bash</span>
                                <span class="border px-2 py-1 rounded font-2">NLP</span>
                                <span class="border px-2 py-1 rounded font-2">CNN</span>
                                <span class="border px-2 py-1 rounded font-2">Docker</span>
                                <span class="border px-2 py-1 rounded font-2">AWS</span>
                                <span class="border px-2 py-1 rounded font-2">Huawei</span>
                                <span class="border px-2 py-1 rounded font-2">DevOps</span>
                                <span class="border px-2 py-1 rounded font-2">Scrum</span>
                                <span class="border px-2 py-1 rounded font-2">Machine Learning</span>
                                <span class="border px-2 py-1 rounded font-2">Deep Learning</span>
                                <span class="border px-2 py-1 rounded font-2">Django</span>
                                <span class="border px-2 py-1 rounded font-2">Git</span>
                                <span class="border px-2 py-1 rounded font-2">CI/CD</span>
                                <span class="border px-2 py-1 rounded font-2">SQL</span>
                            </div>
                        </div>
                    </article>
                    <article class="col-md-5">
                        <h4 class="fw-bold font-3 mb-3"><i class="bi bi-briefcase me-3"></i>WORK EXPERIENCE</h4>
                        <hr>
                        <div class="row pt-2">
                            <article class="mb-1">
                                <h5 class="font-2">Huawei ICT Academy</h5>
                                <p class="font-2" style="margin-top: -10px;">Internship</p>
                            </article>
                            <article class="mb-1">
                                <h5 class="font-2">Google Developer Students Club</h5>
                                <p class="font-2" style="margin-top: -10px;">Trainer</p>
                            </article>
                            <article class="mb-1">
                                <h5 class="font-2">Artificial Intelligence Club</h5>
                                <p class="font-2" style="margin-top: -10px;">Admin/Trainer</p>
                            </article>
                        </div>
                    </article>
                </div>
            </div>            
        </div>
        
        <script src="{% static 'main/script.js' %}"></script>
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    </body>
</html>

portfolio/main/templates/main/view_project.html
{% extends 'main/layout.html' %}
{% load static %}
{% block header %}
    <title>{{ project.title }}</title>
{% endblock %}
{% block content %}
    <canvas id="bgCanvas"></canvas>
    <div class="container min-height p-md-5 p-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'main:home' %}" class="text-decoration-none"><span class="text-danger font-2 ">Home</span></a></li>
                <li class="breadcrumb-item"><a href="{% url 'main:projects' %}" class="text-decoration-none"><span class="text-danger font-2">All projects</span></a></li>
                <li class="breadcrumb-item active" aria-current="page"><span class="font-2">{{ project.title }}</span></li>
            </ol>
        </nav>
        <div class="d-flex justify-content-center align-items-center hidden my-md-5 my-3">
            <img class="shadow-lg" src="{{ project.image_url }}" alt="{{ project.title }}" style="max-width: 100%; max-height: 60vh; object-fit: contain;">
        </div>
        <div id="readme-container" class="bg-light border shadow-lg rounded p-4"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script>
    const repoUrl = "https://raw.githubusercontent.com/abdullashahzan/{{repo_name}}/refs/heads/main/readme.md"; // replace dynamically with project.url if you have it
    fetch(repoUrl)
    .then(response => response.text())
    .then(markdown => {
    document.getElementById("readme-container").innerHTML = marked.parse(markdown);
    })
    .catch(error => {
    console.error("Error loading README:", error);
    document.getElementById("readme-container").innerHTML = "<p>Could not load README.</p>";
    });
    </script>
{% endblock %}